version: "3.8"

services:
  duluin_ml_kit:
    build: .
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - ./environment/.env.staging

    volumes:
      - ./face_datasets:/app/face_datasets
      - ./logs:/app/logs
      - ./vector_db:/app/vector_db
